### ISSUE TITLE
No Internet when iBlocker DNS used

### ISSUE THREAD

**Issue by iBlocker-eu** [iBlocker-eu/iBlocker#5]
**Browsing not possible from PC/smartphone attached to iBlocker**, but ping and tracert from a client PC working fine:
e.g. **ping 8.8.8.8**
Pinging 8.8.8.8 with 32 bytes of data:
Reply from 8.8.8.8: bytes=32 time=41ms TTL=118
Reply from 8.8.8.8: bytes=32 time=28ms TTL=118

e.g. **tracert 8.8.8.8**
Tracing route to dns.google [8.8.8.8]
over a maximum of 30 hops:
  1     1 ms     1 ms     1 ms  172.25.1.1
....
9    36 ms    33 ms    28 ms  dns.google [8.8.8.8]

e.g. **nslookup www.yahoo.com 8.8.8.8**
Server:  dns.google
Address:  8.8.8.8

Non-authoritative answer:
Name:    www.yahoo.com
Address:  170.178.X.Y

**Comment by iBlocker-eu** [comment]
**Solution:**
Modify line from /etc/dhcp/dhcpd.conf
 **option domain-name-servers 172.25.1.1;**
to
**option domain-name-servers 172.25.1.1, 8.8.8.8;**

and restart DHCP as below
**systemctl restart isc-dhcp-server.service**

and **re-attach the client PC to iBlocker Wifi.**

**Comment by cvasil-vlc** [comment]
Profesional, danke!

**Comment by cvasil-vlc** [comment]
Shefu'

Da' nu mi-ai cerut feedback despre cat de multumit sunt de cum ai rezolvat
issue-ul? :) :)
